[package]
name = "gitignore_ultimate_server"
version = "0.1.0"
edition = "2021"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.tower-lsp]
version = "*"

[dependencies.ultimate-server-core]
git = "https://github.com/quentinguidee/ultimate-server-core"
# tag = "0.0.0"
