name: Build

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            extension: ".exe"
          - os: macos-latest
            target: x86_64-apple-darwin
            extension: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extension: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --target ${{ matrix.target }}

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}${{ matrix.extension }}
          path: target/${{ matrix.target }}/debug/gitignore_ultimate_server${{ matrix.extension }}
